---
# tasks file for mysql

- name: add passwd
  shell: sudo debconf-set-selections <<< 'mysql-server-5.6 mysql-server/root_password password root'

- name: add passwd
  shell: sudo debconf-set-selections <<< 'mysql-server-5.6 mysql-server/root_password_again password root'

- name: install mysql 5.6
  apt:
    name: "{{ mysql_pack }}"
    state: present

- name: Create database
  mysql_db: db="{{ mysql_db }}" state=present

