---
# tasks file for tomcati

- name: untar tomcat server one
  unarchive:
    src: "{{ tomcat_tar }}"
    dest: "{{ tomcat1_path }}"

- name: untar tomcat server two
  unarchive:
    src: "{{ tomcat_tar }}"
    dest: "{{ tomcat2_path }}"

- name: copy mysql jar file
  copy:
    src: "{{ mysqljar }}"
    dest: "{{ tomcat1_lib }}"
    owner: root
    group: root
    mode: 0644

- name: copy mysql jar file server one
  copy:
    src: "{{ mysqljar }}"
    dest: "{{ tomcat2_lib }}"
    owner: root
    group: root
    mode: 0644

- name: copy mysql jar file server one
  copy:
    src: "{{ petstore_deploy }}"
    dest: "{{ tomcat1_webapps }}"
    owner: root
    group: root
    mode: 0777

- name: copy petstore ear file server two
  copy:
    src: "{{ petstore_deploy }}"
    dest: "{{ tomcat2_webapps }}"
    owner: root
    group: root
    mode: 0777

- name: copy tomcat1 service
  template: 
    src: "{{ service_tomcat1 }}"
    dest: "{{ service_path }}"

- name: copy tomcat2 service
  template:
    src: "{{ service_tomcat2 }}"
    dest: "{{ service_path }}"

- name: copy tomcat2 server.xml file
  template:
    src: server.xml
    dest: /usr/share/tomcat2/conf/

- name: start service tomcat1
  service:
    name: "{{ service_tomcat1 }}"
    state: started

- name: start service tomcat2
  service:
    name: "{{ service_tomcat2 }}"
    state: started
